[project]
name = "stable-basin"
version = "0.1.0"
description = "Stable Basin"

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = [
    "F",  # pyflakes
    "E",  # pycodestyle (includes E501 for line length)
    "C4", # flake8-comprehensions
    "B",  # flake8-bugbear
]
ignore = ["F401", "E501", "E402"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]

[tool.pyright]
reportUnusedImport = false
