[pytest]
norecursedirs = icebox
markers =
    integration: mark a test as an integration test.
filterwarnings =
    ignore::DeprecationWarning
    ignore:.*deprecated.*:Warning
    ignore:.*ComplexWarning.*
    ignore:.*SVD optimal rank is 0.*
